#cloud-config
users:
  - default
  - name: appuser
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: true
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPbWh7uckaGw+v9tlDnRRyMnmhfXKNvwH/j6k3lP8dl/ s@shitenkov.ru
write_files:
- content: |
    #!/bin/bash
    cd
    wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
    echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
    sudo apt-get update
    sudo apt-get install -y mongodb-org
    sudo systemctl start mongod
    sudo systemctl enable mongod
    git clone -b monolith "https://github.com/express42/reddit.git"
    cd reddit && bundle install
    puma -d
    exit 0
  path: /tmp/deploy.sh
  permissions: '0755'

packages:
  - ruby-full
  - ruby-bundler
  - build-essential
  - git
package_update: true

runcmd:
  - [ su, -c, /tmp/deploy.sh, appuser ]
